name: Security CI Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Сборка проекта без запуска unit-тестов
      - name: Build with Maven
        run: mvn clean compile test-compile -DskipTests

      # SAST
      - name: Run SAST with SpotBugs & FindSecBugs
        run: mvn spotbugs:check -Dspotbugs.failOnError=false

        # папку reports для 2 файлов
      - name: Prepare reports directory
        run: |
          mkdir -p reports
          chmod 777 reports


      # SCA: OWASP Dependency-Check
      - name: Run SCA with OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'infSecLab1'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: '--noupdate'

      - name: Move reports to target
        if: always()
        run: |
          sudo chmod -R 777 reports target || true
          cp reports/dependency-check-report.html target/spotbugsXml.xml || true
          echo "Проверка файлов в target"
          ls -la target/dependency-check-report.html target/spotbugsXml.xml || true


      # Сохранение артефактов
      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            target/spotbugsXml.xml
            target/dependency-check-report.html